apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240113190119.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240113190119.0.0+build.02e9424
  releaseNotes: |
    Release v20240113190119.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-13-01-2024-13-18-28-457978509/where-for-dinner-my-apps-bundle@sha256:7a7ee2464ef16e0b34ae77d992c9589fbfd74038341c98b071a82ecbda9352da
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

